version: '3'

services:
  db:
    image: nouchka/sqlite3
    container_name: db
    volumes:
      - db_data:/var/lib/sqlite3
    networks:
      - backend

  data_processing:
    build: ./data_processing
    container_name: data_processing
    environment:
      - API_KEY=001c2554cc486bf50b3c05b32d468e1b
    depends_on:
      - db
    volumes:
      - ./data_processing:/app
    networks:
      - backend

  api:
    build: ./api
    container_name: api
    depends_on:
      - db
    volumes:
      - ./api:/app
    ports:
      - "5001:80"
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
  frontend:
