version: '3.8'

services:
  db:
    image: nouchka/sqlite3
    container_name: db
    volumes:
      - db_data:/db

  data_loader:
    build:
      context: ./data_processing
    container_name: data_loader
    volumes:
      - db_data:/db
    environment:
      API_KEY: ${API_KEY}
    depends_on:
      - db

  api:
    build:
      context: ./api
    container_name: api
    volumes:
      - db_data:/db
    ports:
      - "8000:80"
    depends_on:
      - db

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - db

  mkdocs:
    build:
      context: ./docs
    container_name: mkdocs
    ports:
      - "8001:8000"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3001:80"
    depends_on:
      - api

volumes:
  db_data:
  grafana_data:
